"""Turn the raw JSONL replies into tables, figures and an error sample.

    python -m escalate.report

Writes to results/: summary.csv, RESULTS.md, error_samples.md and figures/.
"""

import argparse
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import yaml  # noqa: E402

from . import data, metrics  # noqa: E402
from .prompts import CONDITIONS  # noqa: E402

SIGNALS = ("verbal", "consistency", "combined")


def load_runs(raw_dir):
    rows = []
    for path in sorted(Path(raw_dir).glob("*.jsonl")):
        with path.open(encoding="utf-8") as f:
            rows += [json.loads(line) for line in f if line.strip()]
    if not rows:
        raise SystemExit(f"no results found in {raw_dir}; run `python -m escalate.run` first")
    df = pd.DataFrame(rows)
    df["correct"] = df["answer"] == df["label"]
    # A reply we could not parse gets confidence 0, so the system would escalate it.
    df["verbal"] = df["confidence"].fillna(0.0).astype(float)
    if df["consistency"].notna().any():
        df["consistency"] = df["consistency"].astype(float)
        df["combined"] = (df["verbal"] + df["consistency"].fillna(0.0)) / 2
    else:
        df["consistency"] = np.nan
        df["combined"] = np.nan
    return df


def summarise(df, cfg):
    rep = cfg["report"]
    rows = []
    for (model, condition), g in df.groupby(["model", "condition"], sort=False):
        correct = g["correct"].to_numpy()
        row = {
            "model": model,
            "condition": condition,
            "n": len(g),
            "accuracy": metrics.accuracy(correct),
            "accuracy_ci": metrics.bootstrap_ci(metrics.accuracy, correct, n=rep["bootstrap"]),
            "parse_failures": float((~g["parsed"]).mean()),
            "gold_retrieved": float(g["gold_retrieved"].mean()) if condition == "retrieved" else np.nan,
        }
        for signal in SIGNALS:
            conf = g[signal].to_numpy()
            if np.isnan(conf).all():
                continue
            row[f"{signal}_ece"] = metrics.ece(correct, conf)
            row[f"{signal}_aurc"] = metrics.aurc(correct, conf)
            row[f"{signal}_aurc_ci"] = metrics.bootstrap_ci(metrics.aurc, correct, conf, n=rep["bootstrap"])
            for rate in rep["escalation_rates"]:
                row[f"{signal}_caught@{int(rate * 100)}"] = metrics.errors_caught(correct, conf, rate)
        row["confident_errors"] = metrics.confident_error_rate(
            correct, g["verbal"].to_numpy(), rep["confident_threshold"]
        )
        rows.append(row)
    return pd.DataFrame(rows)


def _fmt(v, pct=True):
    if isinstance(v, tuple):
        return f"[{_fmt(v[0], pct)}, {_fmt(v[1], pct)}]"
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "-"
    if isinstance(v, float):
        return f"{100 * v:.1f}" if pct else f"{v:.3f}"
    return str(v)


def md_table(frame, columns, pct_cols=()):
    head = "| " + " | ".join(label for _, label in columns) + " |"
    sep = "|" + "|".join("---" for _ in columns) + "|"
    body = []
    for _, r in frame.iterrows():
        cells = [_fmt(r.get(col), col in pct_cols) for col, _ in columns]
        body.append("| " + " | ".join(cells) + " |")
    return "\n".join([head, sep, *body])


def write_markdown(summary, cfg, path):
    rate = int(100 * cfg["report"]["escalation_rates"][len(cfg["report"]["escalation_rates"]) // 2])
    thr = int(100 * cfg["report"]["confident_threshold"])
    pct = {"accuracy", "accuracy_ci", "parse_failures", "gold_retrieved", "confident_errors",
           f"verbal_caught@{rate}", f"consistency_caught@{rate}", f"combined_caught@{rate}"}
    main_cols = [
        ("model", "Model"), ("condition", "Condition"), ("n", "n"),
        ("accuracy", "Accuracy %"), ("accuracy_ci", "95% CI"),
        ("confident_errors", f"Confident errors % (conf >= {thr})"),
        ("parse_failures", "Unparsed %"), ("gold_retrieved", "Right abstract retrieved %"),
    ]
    sel_cols = [("model", "Model"), ("condition", "Condition")]
    for s in SIGNALS:
        if f"{s}_aurc" in summary:
            sel_cols += [(f"{s}_ece", f"ECE ({s})"), (f"{s}_aurc", f"AURC ({s})"),
                         (f"{s}_caught@{rate}", f"Errors caught @{rate}% ({s})")]
    text = [
        "# Results",
        "",
        "Generated by `python -m escalate.report`. Percentages unless noted; ECE and AURC are on a 0-1 scale, lower is better.",
        "",
        "## Accuracy and confident errors",
        "",
        md_table(summary, main_cols, pct),
        "",
        "## Selective answering",
        "",
        f"*Errors caught @{rate}%*: escalate the {rate}% least confident questions; share of all errors that were among them.",
        "",
        md_table(summary, sel_cols, pct),
        "",
    ]
    Path(path).write_text("\n".join(text), encoding="utf-8")


def plot_risk_coverage(df, out_dir, signal="verbal"):
    for model, g in df.groupby("model"):
        fig, ax = plt.subplots(figsize=(5.5, 4))
        for condition in CONDITIONS:
            c = g[g["condition"] == condition]
            if c.empty:
                continue
            cov, risk = metrics.risk_coverage(c["correct"].to_numpy(), c[signal].to_numpy())
            ax.plot(cov, risk, label=condition.replace("_", " "))
        ax.set_xlabel("Coverage (share of questions answered)")
        ax.set_ylabel("Error rate among answered")
        ax.set_title(f"Risk-coverage, {model} ({signal} confidence)")
        ax.grid(alpha=0.3)
        ax.legend()
        fig.tight_layout()
        fig.savefig(out_dir / f"risk_coverage__{model}__{signal}.png", dpi=150)
        plt.close(fig)


def plot_reliability(df, out_dir, bins=10):
    for model, g in df.groupby("model"):
        conds = [c for c in CONDITIONS if (g["condition"] == c).any()]
        fig, axes = plt.subplots(1, len(conds), figsize=(4 * len(conds), 4), squeeze=False)
        for ax, condition in zip(axes[0], conds):
            c = g[g["condition"] == condition]
            conf, correct = c["verbal"].to_numpy(), c["correct"].to_numpy()
            idx = np.minimum((conf * bins).astype(int), bins - 1)
            centers = (np.arange(bins) + 0.5) / bins
            acc = [correct[idx == b].mean() if (idx == b).any() else np.nan for b in range(bins)]
            counts = [(idx == b).sum() for b in range(bins)]
            ax.bar(centers, acc, width=1 / bins, edgecolor="black", alpha=0.7)
            ax.plot([0, 1], [0, 1], "--", color="grey")
            for x, y, k in zip(centers, acc, counts):
                if k:
                    ax.text(x, (0 if np.isnan(y) else y) + 0.02, str(k), ha="center", fontsize=7)
            ax.set_xlim(0, 1)
            ax.set_ylim(0, 1.05)
            ax.set_xlabel("Stated confidence")
            ax.set_ylabel("Actual accuracy")
            ax.set_title(condition.replace("_", " "))
        fig.suptitle(f"Reliability, {model} (numbers = questions per bin)")
        fig.tight_layout()
        fig.savefig(out_dir / f"reliability__{model}.png", dpi=150)
        plt.close(fig)


def plot_confident_errors(summary, out_dir):
    pivot = summary.pivot(index="model", columns="condition", values="confident_errors")
    pivot = pivot[[c for c in CONDITIONS if c in pivot.columns]] * 100
    ax = pivot.plot.bar(figsize=(6, 4), rot=0)
    ax.set_ylabel("Confident errors (% of questions)")
    ax.set_title("Wrong answers the system would not escalate")
    ax.grid(axis="y", alpha=0.3)
    plt.tight_layout()
    plt.savefig(out_dir / "confident_errors.png", dpi=150)
    plt.close()


def write_error_samples(df, questions, path, per_group=10):
    lines = ["# Confident errors for manual review", "",
             "Highest-confidence wrong answers per model and condition. Read each one and note",
             "why it went wrong (see the categories in the README).", ""]
    for (model, condition), g in df.groupby(["model", "condition"], sort=False):
        wrong = g[~g["correct"]].sort_values("verbal", ascending=False).head(per_group)
        if wrong.empty:
            continue
        lines += [f"## {model} / {condition}", ""]
        for _, r in wrong.iterrows():
            lines += [
                f"- **{r['id']}**: {questions.get(r['id'], '?')}",
                f"  - label `{r['label']}`, model `{r['answer']}` at {100 * r['verbal']:.0f}% confidence",
                "  - category: ",
            ]
        lines.append("")
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", default="config.yaml")
    args = ap.parse_args()
    cfg = yaml.safe_load(Path(args.config).read_text(encoding="utf-8"))

    out = Path(cfg["output_dir"])
    figures = out / "figures"
    figures.mkdir(parents=True, exist_ok=True)

    df = load_runs(out / "raw")
    summary = summarise(df, cfg)
    summary.to_csv(out / "summary.csv", index=False)
    write_markdown(summary, cfg, out / "RESULTS.md")

    plot_risk_coverage(df, figures, "verbal")
    if df["consistency"].notna().any():
        plot_risk_coverage(df, figures, "consistency")
    plot_reliability(df, figures)
    plot_confident_errors(summary, figures)

    questions = {it.id: it.question for it in data.load(cfg["data"]["path"])}
    write_error_samples(df, questions, out / "error_samples.md")
    print(f"wrote {out / 'RESULTS.md'}, {out / 'summary.csv'}, {out / 'error_samples.md'} and {figures}/")


if __name__ == "__main__":
    main()
